import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { findByAdminUserId } from '@/lib/db/schools';
import { create as createStudent } from '@/lib/db/students';
import { create as createFee } from '@/lib/db/fees';
import { create as createAccount } from '@/lib/db/virtual-accounts';
import { create as createMisdirected } from '@/lib/db/misdirected';
import { getNombaProvider } from '@/lib/nomba';
import { generateAccountRef } from '@/lib/nomba/nuban';
import { CURRENT_TERM } from '@/lib/constants';

export async function POST() {
  if (process.env.NOMBA_PROVIDER !== 'mock') {
    return NextResponse.json({ error: 'Mock endpoints disabled in live mode' }, { status: 404 });
  }

  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const school = await findByAdminUserId(user.id);
  if (!school) return NextResponse.json({ error: 'No school found' }, { status: 403 });

  const provider = getNombaProvider();

  const mockStudents = [
    { first: 'John', last: 'Doe', class: 'JSS1', expected: 50000, paid: 35000 },     // Underpaid
    { first: 'Jane', last: 'Smith', class: 'SSS3', expected: 50000, paid: 50000 },   // Complete
    { first: 'Alice', last: 'Johnson', class: 'JSS2', expected: 50000, paid: 55000 },// Overpaid
    { first: 'Bob', last: 'Williams', class: 'SSS1', expected: 45000, paid: 0 },     // Pending
    { first: 'Charlie', last: 'Brown', class: 'JSS3', expected: 60000, paid: 30000 },// Underpaid
  ];

  const results = [];

  for (const ms of mockStudents) {
    const student = await createStudent({
      school_id: school.id,
      first_name: ms.first,
      last_name: ms.last,
      class_level: ms.class,
    });

    await createFee({
      student_id: student.id,
      amount_expected: ms.expected,
      term: CURRENT_TERM,
    });

    const accountRef = generateAccountRef(student.id);
    const nombaRes = await provider.createVirtualAccount({
      accountRef,
      accountName: `${ms.first} ${ms.last}`,
    });

    const accountData = nombaRes.data;

    await createAccount({
      student_id: student.id,
      school_id: school.id,
      nomba_account_ref: accountRef,
      nomba_account_holder_id: accountData.accountHolderId,
      account_number: accountData.bankAccountNumber,
      account_name: accountData.accountName,
      status: 'active',
    });

    if (ms.paid > 0) {
      // simulate webhook
      await fetch(new URL('/api/mock/webhook', process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000').toString(), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          accountRef,
          amount: ms.paid,
          senderName: `${ms.first} Parent`,
        }),
      });
    }

    results.push(student);
  }

  // Create one misdirected payment
  await createMisdirected({
    school_id: school.id,
    nomba_account_ref: 'unknown_ref_999',
    nomba_txn_ref: 'mock_txn_misdirected',
    amount: 15000,
    currency: 'NGN',
    sender_name: 'Unknown Sender',
    payment_method: 'transfer',
    raw_payload: { note: 'Generated by demo setup' },
  });

  return NextResponse.json({ success: true, created: results.length });
}
